# Generated by Django 3.0.2 on 2020-07-19 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemlink',
            old_name='wish_list_item',
            new_name='item',
        ),
    ]
