# Generated by Django 3.0.2 on 2020-07-19 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20200718_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemlink',
            name='owner',
        ),
    ]
