# Generated by Django 3.0.2 on 2020-09-06 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20200829_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='deactivate_after',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='group',
            name='public_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_purchased',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='wish_list',
            field=models.ManyToManyField(related_name='wish_lists', to='project.WishList'),
        ),
        migrations.AlterField(
            model_name='itemlink',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemlink',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_links', to='project.Item'),
        ),
        migrations.AlterField(
            model_name='itemlink',
            name='link',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='itemlink',
            name='name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='groups',
            field=models.ManyToManyField(related_name='groups', to='project.Group'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='private_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='public_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
