# Generated by Django 3.0.2 on 2020-09-07 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pendulum
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0003_auto_20200906_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=pendulum.now, editable=False)),
                ('lastUpdated', models.DateTimeField(default=pendulum.now)),
                ('name', models.TextField(blank=True, default='')),
                ('public_note', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('members', models.ManyToManyField(related_name='group_member', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='groups',
            field=models.ManyToManyField(related_name='groups', to='project.AppGroup'),
        ),
    ]
