# Generated by Django 3.0.2 on 2020-07-19 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_itemlink_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlink',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_link', to='project.Item'),
        ),
    ]
