# Generated by Django 3.0.2 on 2020-07-19 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20200719_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemlink',
            name='item',
        ),
    ]
