# Generated by Django 3.0.2 on 2020-07-19 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20200719_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemlink',
            name='item',
        ),
    ]
